// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjft_soD-4AAVE35pUJtGfYpaS42JGPDU',
    appId: '1:157686685798:web:42e79efb41816ed75e8da7',
    messagingSenderId: '157686685798',
    projectId: 'minimalchat-93772',
    authDomain: 'minimalchat-93772.firebaseapp.com',
    storageBucket: 'minimalchat-93772.appspot.com',
    measurementId: 'G-Z756P2QGJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7OEgWLdLsAjfY-yBHIS4EFa-K5Xd7RQ',
    appId: '1:157686685798:android:3dd879441fab50fc5e8da7',
    messagingSenderId: '157686685798',
    projectId: 'minimalchat-93772',
    storageBucket: 'minimalchat-93772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4fD4uYLJ3VHpY7tV2Vxp9Szr5i9LrZk',
    appId: '1:157686685798:ios:ec6ee73c461aac915e8da7',
    messagingSenderId: '157686685798',
    projectId: 'minimalchat-93772',
    storageBucket: 'minimalchat-93772.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj4fD4uYLJ3VHpY7tV2Vxp9Szr5i9LrZk',
    appId: '1:157686685798:ios:ec6ee73c461aac915e8da7',
    messagingSenderId: '157686685798',
    projectId: 'minimalchat-93772',
    storageBucket: 'minimalchat-93772.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjft_soD-4AAVE35pUJtGfYpaS42JGPDU',
    appId: '1:157686685798:web:86e6d79ca5d45b585e8da7',
    messagingSenderId: '157686685798',
    projectId: 'minimalchat-93772',
    authDomain: 'minimalchat-93772.firebaseapp.com',
    storageBucket: 'minimalchat-93772.appspot.com',
    measurementId: 'G-NJ2RNW1DFG',
  );

}